live_config_reload = true

[window]
opacity = 0.7
#startup_mode = "Fullscreen"
#decorations = "None" # 
blur = true
dynamic_title = false

[window.padding]
x = 1
y = 0

[scrolling]
history = 25000

[cursor]
unfocused_hollow = false
thickness = 0.01

[cursor.style]
shape = "Beam"
blinking = "On"

[mouse]
hide_when_typing = true
bindings =  [
    { mouse = "Middle", action = "Paste" },
    { mouse = "Right", action = "Copy" },
]

[font]
normal = { family = "FiraCode Nerd Font" }
size = 13.0
