live_config_reload = true
working_directory = "None"

[window]
opacity = 0.9
# startup_mode = "Fullscreen"
decorations = "Full"
blur = true
dynamic_title = true

[window.padding]
x = 7
y = 0

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font"

[scrolling]
history = 25000

# animation = "Ease" | "EaseOut" | "EaseOutSine" | "EaseOutQuad" | "EaseOutCubic" | "EaseOutQuart" | "EaseOutQuint" | "EaseOutExpo" | "EaseOutCirc" | "Linear"
[bell]
animation = "EaseOutSine"
duration = 125

[cursor]
unfocused_hollow = false
thickness = 0.01

[cursor.style]
shape = "Beam"
blinking = "On"

[mouse]
hide_when_typing = true
bindings =  [
    { mouse = "Middle", action = "Paste" },
    { mouse = "Right", action = "Copy" },
]

# If Windows WSL2
# import = [
#  "C:/Users/bernh/AppData/Roaming/alacritty/shell-wsl2.toml"
# ]

# Copyright (c) 2016-present Sven Greb <development@svengreb.de>
# This source code is licensed under the MIT license found in the license file.

colors:
  primary:
    background: "#2e3440"
    foreground: "#d8dee9"
    dim_foreground: "#a5abb6"
  cursor:
    text: "#2e3440"
    cursor: "#d8dee9"
  vi_mode_cursor:
    text: "#2e3440"
    cursor: "#d8dee9"
  selection:
    text: CellForeground
    background: "#4c566a"
  search:
    matches:
      foreground: CellBackground
      background: "#88c0d0"
    bar:
      background: "#434c5e"
      foreground: "#d8dee9"
  normal:
    black: "#3b4252"
    red: "#bf616a"
    green: "#a3be8c"
    yellow: "#ebcb8b"
    blue: "#81a1c1"
    magenta: "#b48ead"
    cyan: "#88c0d0"
    white: "#e5e9f0"
  bright:
    black: "#4c566a"
    red: "#bf616a"
    green: "#a3be8c"
    yellow: "#ebcb8b"
    blue: "#81a1c1"
    magenta: "#b48ead"
    cyan: "#8fbcbb"
    white: "#eceff4"
  dim:
    black: "#373e4d"
    red: "#94545d"
    green: "#809575"
    yellow: "#b29e75"
    blue: "#68809a"
    magenta: "#8c738c"
    cyan: "#6d96a5"
    white: "#aeb3bb"
