#!/bin/bash

set -e
CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -x "$(command -v apk)" ]; then
  apk update
  apk add git bash python3
fi

touch "${BASEDIR}/${CONFIG}"
cat "${BASEDIR}/install.conf.general.yaml" >"${BASEDIR}/${CONFIG}"

declare -a arr=("brew" "apt" "snap" "apk")

for i in "${arr[@]}"
do
  if [ -x "$(command -v $i)" ]; then
    cat "${BASEDIR}/install.conf.${i}.yaml" >>"${BASEDIR}/${CONFIG}"
  fi
done

if [ -n "${GITHUB_CODESPACE_TOKEN}" ]; then
  cat "${BASEDIR}/install.conf.codespace.yaml" >>"${BASEDIR}/${CONFIG}"
fi

if [ "$(whoami)" == "rbo2abt" ]; then
  cat "${BASEDIR}/install.conf.bosch.yaml" >>"${BASEDIR}/${CONFIG}"
fi

if [ "$(whoami)" == "ebbo" ]; then
  cat "${BASEDIR}/install.conf.private.yaml" >>"${BASEDIR}/${CONFIG}"
fi

cd "${BASEDIR}"

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

if [ -f "${BASEDIR}/${CONFIG}" ]; then
  rm "${BASEDIR}/${CONFIG}"
fi

rm -f ~/.zshrc.pre-oh-my-zsh-*
rm -f ~/.zshrc_*
rm -f .zcompdum*

cat "${BASEDIR}/install.conf.banner.yaml" >>"${BASEDIR}/${CONFIG}"
