default:
  margin:
    percent: 8
  colors:
    foreground: "D0D4D8"
    background: "232628"

intro_slide:
  title:
    alignment: center
    colors:
      foreground: "E6007E"
  subtitle:
    alignment: center
    padding_bottom: 1
    padding_top: 1
    colors:
      foreground: "0096e8"
  author:
    alignment: center
    colors:
      foreground: "8e9aaf"
    positioning: page_bottom

footer:
  style: template
  left: "Techboard"
  center: ""
  right: "{current_slide} / {total_slides}"
  colors:
    foreground: "1a1c1d"

slide_title:
  alignment: center
  padding_bottom: 1
  padding_top: 1
  bold: true

headings:
  alignment: center
  h1:
    prefix: "██"
    colors:
      foreground: "008ECF"
  h2:
    prefix: "▓▓▓"
    colors:
      foreground: "78BE20"
  h3:
    prefix: "▒▒▒▒"
    colors:
      foreground: "E6007E"
  h4:
    prefix: "░░░░░"
    colors:
      foreground: "E6007E"
  h5:
    prefix: "░░░░░░"
    colors:
      foreground: "E6007E"
  h6:
    prefix: "░░░░░░░"
    colors:
      foreground: "E6007E"
#   padding_bottom: 1
#   padding_top: 1
#   colors:
#     foreground: "f77f00"
#
# code:
#   alignment: center
#   minimum_size: 50
#   minimum_margin:
#     percent: 8
#   theme_name: GitHub
#   padding:
#     horizontal: 2
#     vertical: 1
#
# execution_output:
#   colors:
#     foreground: "212529"
#     background: "e9ecef"
#
# inline_code:
#   colors:
#     foreground: "f07167"
#     background: "f5cac3"
#
#
# headings:
#   h1:
#     prefix: "->"
#     colors:
#       foreground: "1d3557"
#   h2:
#     prefix: "--->"
#     colors:
#       foreground: "457b9d"
#   h3:
#     prefix: "▒▒▒▒"
#     colors:
#       foreground: "4a4e69"
#   h4:
#     prefix: "░░░░░"
#     colors:
#       foreground: "4a4e69"
#   h5:
#     prefix: "░░░░░░"
#     colors:
#       foreground: "4a4e69"
#   h6:
#     prefix: "░░░░░░░"
#     colors:
#       foreground: "4a4e69"
#
# block_quote:
#   prefix: "▍ "
#   colors:
#     foreground: "212529"
#     background: "e9ecef"
#     prefix: "f77f00"
#
# typst:
#   colors:
#     foreground: "212529"
#     background: "e9ecef"
#
# modals:
#   selection_colors:
#     foreground: "f77f00"
