# Functions
source ~/.config/shell/functions.sh

# Allow local customizations in the ~/.shell_local_before file
if [ -f ~/.config/shell_local_before ]; then
  source ~/.config/shell_local_before
fi

# Allow local customizations in the ~/.bashrc_local_before file
if [ -f ~/.config/bashrc_local_before ]; then
  source ~/.config/bashrc_local_before
fi

# Settings
source ~/.config/bash/settings.bash

# Bootstrap
source ~/.config/shell/bootstrap.sh

# Colors
source ~/.config/shell/colors.sh

# External settings
source ~/.config/shell/external.sh

# Path
source ~/.config/shell/path.sh

# Aliases
source ~/.config/shell/aliases.sh

# Plugins
source ~/.config/bash/plugins.bash

# Allow local customizations in the ~/.shell_local_after file
if [ -f ~/config/.shell_local_after ]; then
  source ~/.shell_local_after
fi

# Allow local customizations in the ~/.bashrc_local_after file
if [ -f ~/config/.bashrc_local_after ]; then
  source ~/config/.bashrc_local_after
fi

# Allow private customizations (not checked in to version control)
if [ -f ~/.shell_private ]; then
  source ~/.shell_private
fi
. "$HOME/.cargo/env"
