# Functions
source ~/.config/shell/functions.sh

# Allow local customizations in the ~/.shell_local_before file
if [ -f ~/.shell_local_before ]; then
    source ~/.shell_local_before
fi

# Settings
source ~/.config/shell/settings.sh
source ~/.config/zsh/settings.zsh

# Bootstrap
source ~/.config/shell/bootstrap.sh

# Path
source ~/.config/shell/path.sh

# External settings
source ~/.config/shell/external.sh

# Aliases
source ~/.config/shell/aliases.sh

# Plugins
source ~/.config/zsh/plugins.zsh

# Oh my zsh
source ~/.config/zsh/oh-my-zsh.zsh
source ~/.config/zsh/auto-suggest.zsh
source ~/.config/zsh/spaceship.zsh

# Allow local customizations in the ~/.shell_local_after file
if [ -f ~/.shell_local_after ]; then
    source ~/.shell_local_after

fi

# Allow local customizations in the ~/.zshrc_local_after file
if [ -f ~/.bashrc_local_after ]; then
    source ~/.zshrc_local_after
fi

# Allow private customizations (not checked in to version control)
if [ -f ~/.shell_private ]; then
    source ~/.shell_private
fi
