github.com:
    user: BernhardRode
    git_protocol: https
    oauth_token: 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
    user: BernhardRode
    git_protocol: https
github.boschdevcloud.com:
    oauth_token: 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
    user: RBO2ABT
    git_protocol: https
