- pacman:
    - bash
    - bzip2
    - coreutils
    - curl
    - direnv
    - eza
    - file
    - gawk
    - gcc
    - git
    # - gnupg2
    - grep
    - gzip
    - jq
    - lzip
    - make
    - ripgrep
    - sed
    - tar
    - tmux
    - unzip
    - util-linux
    # - xz-utils
    - zsh
    - zstd
